name: Publish appcast
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag name
        required: true
jobs:
  publish:
    runs-on: macos-latest
    env:
      ARCHIVE_NAME: Cocotodon-${{ github.event.inputs.tag }}.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bundle install

      - name: Make temp dir
        run: mkdir -p ${{ github.workspace }}/tmp
      
      - name: Download sparkle tools
        working-directory: tmp
        run: |
          curl -Lo Sparkle.tar.xz https://github.com/sparkle-project/Sparkle/releases/download/1.26.0/Sparkle-1.26.0.tar.xz
          mkdir Sparkle
          tar -Jxf Sparkle.tar.xz -C Sparkle

      - name: Download specified release
        working-directory: tmp
        run: |
          curl -Lo "${{ env.ARCHIVE_NAME }}" "https://github.com/shibafu528/Cocotodon/releases/download/${{ github.event.inputs.tag }}/${{ env.ARCHIVE_NAME }}"

      - name: Generate version metadata
        run: ruby generate_item.rb --tag "${{ github.event.inputs.tag }}" --archive "${{ github.workspace }}/tmp/${{ env.ARCHIVE_NAME }}"
        env:
          SPARKLE_PRIVATE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release note and appcast.xml
        run: ruby generate_xml.rb --public public --versions versions

      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: .
          message: auto-generate release ${{ github.event.inputs.tag }}
          push: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
